services:
  postgres:
    image: postgres:17
    container_name: medispheres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: medispheres
      POSTGRES_USER: medispheres_user
      POSTGRES_PASSWORD: medispheres_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: