import { useEffect, useState } from "react";
import {
  Activity,
  AlertCircle,
  FileText,
  ShieldCheck,
  Users,
} from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import DashboardLayout from "../../layout/DashboardLayout";
import { apiRequest } from "../../services/api";

function AdminDashboard() {
  const { user } = useAuth();

  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const fetchAuditLogs = async () => {
    try {
      setLoading(true);
      setError("");

      const data = await apiRequest("/audit-logs");
      setLogs(data.logs);
    } catch (error) {
      setError(error.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAuditLogs();
  }, []);

  const createLogs = logs.filter(
    (log) => log.action === "CREATE"
  ).length;

  const readLogs = logs.filter(
    (log) => log.action === "READ"
  ).length;

  const updateLogs = logs.filter(
    (log) => log.action === "UPDATE"
  ).length;

  const currentHour = new Date().getHours();

  const greeting =
    currentHour < 12
      ? "Good morning"
      : currentHour < 18
        ? "Good afternoon"
        : "Good evening";

  const getActionClasses = (action) => {
    switch (action) {
      case "CREATE":
        return "bg-emerald-50 text-emerald-700";

      case "READ":
        return "bg-blue-50 text-blue-700";

      case "UPDATE":
        return "bg-amber-50 text-amber-700";

      case "DELETE":
        return "bg-red-50 text-red-700";

      default:
        return "bg-slate-100 text-slate-600";
    }
  };

  return (
    <DashboardLayout>
      {/* Header */}
      <section>
        <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
          <div>
            <p className="text-sm font-medium text-blue-600">
              Administration
            </p>

            <h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">
              {greeting}
            </h1>

            <p className="mt-2 text-sm text-slate-500">
              Monitor system activity and security events.
            </p>
          </div>

          <div className="text-sm text-slate-500">
            Signed in as{" "}
            <span className="font-medium text-slate-700">
              {user.email}
            </span>
          </div>
        </div>
      </section>

      {/* Security Banner */}
      <section className="mt-8">
        <div className="flex items-start gap-4 rounded-2xl border border-blue-200 bg-blue-50 p-5">
          <div className="rounded-xl bg-white p-3 text-blue-600 shadow-sm">
            <ShieldCheck size={21} />
          </div>

          <div>
            <h2 className="font-semibold text-blue-900">
              Security & Audit Monitoring
            </h2>

            <p className="mt-1 text-sm leading-6 text-blue-700">
              Review recent system activity and audit events
              generated by authenticated users.
            </p>
          </div>
        </div>
      </section>

      {/* Summary Cards */}
      <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-sm font-medium text-slate-500">
                Total Events
              </p>

              <p className="mt-2 text-3xl font-bold text-slate-900">
                {logs.length}
              </p>
            </div>

            <div className="rounded-xl bg-blue-50 p-3 text-blue-600">
              <Activity size={20} />
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-sm font-medium text-slate-500">
                Create Events
              </p>

              <p className="mt-2 text-3xl font-bold text-slate-900">
                {createLogs}
              </p>
            </div>

            <div className="rounded-xl bg-emerald-50 p-3 text-emerald-600">
              <FileText size={20} />
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-sm font-medium text-slate-500">
                Read Events
              </p>

              <p className="mt-2 text-3xl font-bold text-slate-900">
                {readLogs}
              </p>
            </div>

            <div className="rounded-xl bg-violet-50 p-3 text-violet-600">
              <Users size={20} />
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-sm font-medium text-slate-500">
                Update Events
              </p>

              <p className="mt-2 text-3xl font-bold text-slate-900">
                {updateLogs}
              </p>
            </div>

            <div className="rounded-xl bg-amber-50 p-3 text-amber-600">
              <AlertCircle size={20} />
            </div>
          </div>
        </div>
      </section>

      {/* Audit Logs */}
      <section className="mt-8 pb-8">
        <div>
          <h2 className="text-xl font-semibold text-slate-900">
            Audit Logs
          </h2>

          <p className="mt-1 text-sm text-slate-500">
            Recent security and application activity.
          </p>
        </div>

        {loading && (
          <div className="mt-4 rounded-xl border border-slate-200 bg-white p-6">
            <p className="text-sm text-slate-500">
              Loading audit logs...
            </p>
          </div>
        )}

        {error && (
          <div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4">
            <p className="text-sm text-red-700">{error}</p>
          </div>
        )}

        {!loading &&
          !error &&
          logs.length === 0 && (
            <div className="mt-4 rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center">
              <Activity
                size={28}
                className="mx-auto text-slate-400"
              />

              <p className="mt-3 font-medium text-slate-700">
                No audit events
              </p>

              <p className="mt-1 text-sm text-slate-500">
                System activity will appear here.
              </p>
            </div>
          )}

        {!loading &&
          !error &&
          logs.length > 0 && (
            <div className="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
              {/* Desktop Table */}
              <div className="hidden overflow-x-auto md:block">
                <table className="w-full text-left">
                  <thead className="border-b border-slate-200 bg-slate-50">
                    <tr>
                      <th className="px-5 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500">
                        Action
                      </th>

                      <th className="px-5 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500">
                        Resource
                      </th>

                      <th className="px-5 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500">
                        User
                      </th>

                      <th className="px-5 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500">
                        Role
                      </th>

                      <th className="px-5 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500">
                        Resource ID
                      </th>

                      <th className="px-5 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500">
                        Timestamp
                      </th>
                    </tr>
                  </thead>

                  <tbody className="divide-y divide-slate-100">
                    {logs.map((log) => (
                      <tr
                        key={log.id}
                        className="transition hover:bg-slate-50"
                      >
                        <td className="px-5 py-4">
                          <span
                            className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${
                              getActionClasses(log.action)
                            }`}
                          >
                            {log.action}
                          </span>
                        </td>

                        <td className="px-5 py-4 text-sm font-medium text-slate-700">
                          {log.resource_type}
                        </td>

                        <td className="px-5 py-4 text-sm text-slate-600">
                          {log.user_email || "Unknown"}
                        </td>

                        <td className="px-5 py-4">
                          <span className="text-sm capitalize text-slate-600">
                            {log.user_role || "Unknown"}
                          </span>
                        </td>

                        <td className="max-w-48 truncate px-5 py-4 font-mono text-xs text-slate-500">
                          {log.resource_id || "N/A"}
                        </td>

                        <td className="whitespace-nowrap px-5 py-4 text-sm text-slate-500">
                          {new Date(
                            log.created_at
                          ).toLocaleString()}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Mobile Cards */}
              <div className="divide-y divide-slate-100 md:hidden">
                {logs.map((log) => (
                  <article
                    key={log.id}
                    className="p-5"
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div>
                        <span
                          className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${
                            getActionClasses(log.action)
                          }`}
                        >
                          {log.action}
                        </span>

                        <h3 className="mt-2 font-medium text-slate-900">
                          {log.resource_type}
                        </h3>
                      </div>

                      <span className="text-xs text-slate-400">
                        {new Date(
                          log.created_at
                        ).toLocaleDateString()}
                      </span>
                    </div>

                    <div className="mt-4 space-y-2 text-sm">
                      <p className="text-slate-600">
                        <span className="font-medium text-slate-700">
                          User:
                        </span>{" "}
                        {log.user_email || "Unknown"}
                      </p>

                      <p className="text-slate-600">
                        <span className="font-medium text-slate-700">
                          Role:
                        </span>{" "}
                        <span className="capitalize">
                          {log.user_role || "Unknown"}
                        </span>
                      </p>

                      <p className="break-all font-mono text-xs text-slate-500">
                        {log.resource_id || "N/A"}
                      </p>

                      <p className="text-xs text-slate-400">
                        {new Date(
                          log.created_at
                        ).toLocaleString()}
                      </p>
                    </div>
                  </article>
                ))}
              </div>
            </div>
          )}
      </section>
    </DashboardLayout>
  );
}

export default AdminDashboard;